server:
  port: 80
spring:
  application:
    name: cloud-order-service
eureka:
  client:
    register-with-eureka: true # 表示注册自己
    fetch-registry: true # 是否从eurekaserver抓取自己的注册信息，单节点无所谓，集群必须为true，才能和ribbon实现负载均衡
    service-url:
      # 设置服务与eureka交互的地址，提供服务注册与发现
      defaultZone: http://localhost:7001/eureka